- hosts: "{{ plat }}"
  become: true
  connection: ssh
  remote_user: "{{ vm_user }}"
  pre_tasks:
    - debug: msg="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  roles:
    - { role: vtc, pop: ncrsd, proj: qual }}
    #- { role: vtu, pop: ncrsd, proj: qual }}
    - { role: vcc, pop: ncrsd, proj: qual }}
    - { role: vcc, pop: alabs, proj: demo }}
