---
# tasks file for docker-vcdn

#- name: Docker User Defined Network (vTC - vTU)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.21.118.0/24 --gateway=172.21.118.1 \
#--ip-range=172.21.118.128/25 "{{ vl_vtc_vtu }}"'

#- name: Docker User Defined Network (vTU -vCC)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.21.119.0/24 --gateway=172.21.119.1 \
#--ip-range=172.21.119.128/25 "{{ vl_vtu_vcc }}"'

#- name: Docker User Defined Network (vTU - SOURCE_CONTENT)
#  shell: 'docker network create --driver=bridge \
#--subnet=172.21.121.0/24 --gateway=172.21.121.1 \
#--ip-range=172.21.121.128/25 "{{ vl_vtu_src }}"'

