---

- name: deploy dockerized VCDN to the local machine
  hosts: localhost
  become: true
  connection: local
#  vars_files:
#    - "{{ lookup('env','PWD') }}/roles/{{ plat | default(vm) }}/vars/os_{{ pop }}_{{ proj }}_{{ distro }}.yml"
  pre_tasks:
    - debug: msg="{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
    - file:
        path: /var/log/ansible.log
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"
      become: true
    - include: "{{ lookup('env','PWD') }}/networks.yml"
  roles:
    - { role: firewall, become: true }
    - { role: docker-vtu, become: true }
    - { role: docker-vtc, become: true }
    - { role: docker-vcc, become: true }

#- include: "{{ lookup('env','PWD') }}/common.yml"
